It's Alive!
Traceback (most recent call last):
  File "/home/yijie/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/yijie/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/visdom/server.py", line 637, in <module>
    main()
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/visdom/server.py", line 625, in main
    app.listen(FLAGS.port, max_buffer_size=1024 ** 3)
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1850, in listen
    server.listen(port, address)
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/tornado/netutil.py", line 194, in bind_sockets
    sock.bind(sockaddr)
  File "/home/yijie/anaconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
It's Alive!
Traceback (most recent call last):
  File "/home/yijie/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/yijie/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/visdom/server.py", line 637, in <module>
    main()
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/visdom/server.py", line 625, in main
    app.listen(FLAGS.port, max_buffer_size=1024 ** 3)
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1850, in listen
    server.listen(port, address)
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/tornado/netutil.py", line 194, in bind_sockets
    sock.bind(sockaddr)
  File "/home/yijie/anaconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
It's Alive!
Traceback (most recent call last):
  File "/home/yijie/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/yijie/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/visdom/server.py", line 637, in <module>
    main()
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/visdom/server.py", line 625, in main
    app.listen(FLAGS.port, max_buffer_size=1024 ** 3)
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1850, in listen
    server.listen(port, address)
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/tornado/tcpserver.py", line 126, in listen
    sockets = bind_sockets(port, address=address)
  File "/home/yijie/anaconda2/lib/python2.7/site-packages/tornado/netutil.py", line 194, in bind_sockets
    sock.bind(sockaddr)
  File "/home/yijie/anaconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
